//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTester.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="RestServiceDomain")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FisrtNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FisrtName {
            get {
                return this.FisrtNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FisrtNameField, value) != true)) {
                    this.FisrtNameField = value;
                    this.RaisePropertyChanged("FisrtName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRestService")]
    public interface IRestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetStringUserFullName", ReplyAction="http://tempuri.org/IRestService/GetStringUserFullNameResponse")]
        string GetStringUserFullName(string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetStringUserFullName", ReplyAction="http://tempuri.org/IRestService/GetStringUserFullNameResponse")]
        System.Threading.Tasks.Task<string> GetStringUserFullNameAsync(string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetStringUserName", ReplyAction="http://tempuri.org/IRestService/GetStringUserNameResponse")]
        string GetStringUserName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetStringUserName", ReplyAction="http://tempuri.org/IRestService/GetStringUserNameResponse")]
        System.Threading.Tasks.Task<string> GetStringUserNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetObjectUser", ReplyAction="http://tempuri.org/IRestService/GetObjectUserResponse")]
        ClientTester.ServiceReference.User GetObjectUser(string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestService/GetObjectUser", ReplyAction="http://tempuri.org/IRestService/GetObjectUserResponse")]
        System.Threading.Tasks.Task<ClientTester.ServiceReference.User> GetObjectUserAsync(string FirstName, string LastName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceChannel : ClientTester.ServiceReference.IRestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceClient : System.ServiceModel.ClientBase<ClientTester.ServiceReference.IRestService>, ClientTester.ServiceReference.IRestService {
        
        public RestServiceClient() {
        }
        
        public RestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStringUserFullName(string FirstName, string LastName) {
            return base.Channel.GetStringUserFullName(FirstName, LastName);
        }
        
        public System.Threading.Tasks.Task<string> GetStringUserFullNameAsync(string FirstName, string LastName) {
            return base.Channel.GetStringUserFullNameAsync(FirstName, LastName);
        }
        
        public string GetStringUserName() {
            return base.Channel.GetStringUserName();
        }
        
        public System.Threading.Tasks.Task<string> GetStringUserNameAsync() {
            return base.Channel.GetStringUserNameAsync();
        }
        
        public ClientTester.ServiceReference.User GetObjectUser(string FirstName, string LastName) {
            return base.Channel.GetObjectUser(FirstName, LastName);
        }
        
        public System.Threading.Tasks.Task<ClientTester.ServiceReference.User> GetObjectUserAsync(string FirstName, string LastName) {
            return base.Channel.GetObjectUserAsync(FirstName, LastName);
        }
    }
}
